more refactoring

diff --git a/bin/bin/functions/dev/dirdiff b/bin/bin/functions/dev/dirdiff
--- a/bin/bin/functions/dev/dirdiff
+++ b/bin/bin/functions/dev/dirdiff
@@ -6,7 +6,7 @@
 
 # ..................................................... Recursive directory diff
 
-usage() { usage: "$(basename $0) [-[1 | s | b | E | Z | EZ]] [-d <date>] <.[/]|[./]source> [<repo|target>] [<regex>]"; exit 1; }
+usage() { usage: "$(basename $0) [-[1 | s | b | E | Z | EZ | debug]] [-d <date>] <.[/]|[./]source> [<repo|target>] [<regex>]"; exit 1; }
 
 # NOTE: dirdiff quickly highlights project source code changes against a (separate) snapshot directory
 #       ./                    -> do not match source path against target
@@ -22,23 +22,25 @@ ignore='backups|debian|\.history|makepkg|nixos|plugged-custom|root|snippets|undo
 
 SNAPSHOT=${SNAPSHOT:-/home/depot/dotfiles}  # default project snapshot
 DIRDIFF=/tmp/dirdiff
-COLORDIFF=colordiff
 FILES=$DIRDIFF:files
 LOG=$DIRDIFF.log
+rm -f $LOG
+
 delay=0.001  # match message animation interval
 
 # Runtime ......................................................................
 
 while [ "$1" ] ;do
 	case $1 in
-		-1  ) unset IC ICOPT ;;                                        # standard diff (not side-by-side)
-		-s  ) S=true         ;;                                        # flash messages
-		-b  ) w=-w; diffopt='set diffopt+=iwhite'  ;;                  # ignore whitespace
-		-E  ) w=-E; diffopt='set diffopt+=iwhite'  ;;                  # ignore whitespace
-		-Z  ) w=-Z; diffopt='set diffopt+=iwhite'  ;;                  # ignore whitespace
-		-EZ ) w=-EZ; diffopt='set diffopt+=iwhite' ;;                  # ignore whitespace
-		-d  ) FILTER=$DIRDIFF:filter; touch -d "$2" $FILTER; shift ;;  # timestamp filter
-		*   ) break ;;
+		-1     ) unset IC ICOPT ;;                                        # standard diff (not side-by-side)
+		-s     ) S=true         ;;                                        # flash messages
+		-b     ) w=-w; diffopt='set diffopt+=iwhite'  ;;                  # ignore whitespace
+		-E     ) w=-E; diffopt='set diffopt+=iwhite'  ;;                  # ignore whitespace
+		-Z     ) w=-Z; diffopt='set diffopt+=iwhite'  ;;                  # ignore whitespace
+		-EZ    ) w=-EZ; diffopt='set diffopt+=iwhite' ;;                  # ignore whitespace
+		-debug ) debug=true; set -x ;;
+		-d     ) FILTER=$DIRDIFF:filter; touch -d "$2" $FILTER; shift ;;  # timestamp filter
+		*      ) break ;;
 	esac
 	shift
 done
@@ -59,11 +61,11 @@ target=${target%/.}
 
 # find matching source directory in target repo
 TARGET=${target:-$SNAPSHOT}  # unprovided target defaults to dotfile repo
-[ -L $TARGET ] && L=-L
-target=$(find $L $TARGET -type ${T:-d} -regex ".*${path#*$P}" 2>/dev/null | head -1)
-[ -${T:-d} "$target" ] || target=$(find $L $TARGET -type ${T:-d} -regex ".*${path#*/stow}" 2>/dev/null | head -1)
+[ -L $TARGET ] && L=-L       # WARNING: find will fail on errant recursive links
+target=$(find $L $TARGET -type ${T:-d} -regex ".*${path#*$P}" | head -1)
+[ -${T:-d} "$target" ] || target=$(find $L $TARGET -type ${T:-d} -regex ".*${path#*/stow}" | head -1)
 
-# $HOME/bin ....................................................................
+# Source bin ...................................................................
 
 # distinguish $HOME/bin from all other application bin folders
 if [ $T ] ;then
@@ -89,30 +91,29 @@ esac
 src=${source#$HOME/stow/*/}
 src=\~/${src#$HOME/}
 
+[ $debug ] && { ditto debug "T=$T target=$target"; exit; }
+
 # Diff .........................................................................
 
 while read file <&3 ;do
 	[ "${file##*.}" = 'log' ] || [ "${file##*.}" = 'jpg' ] && continue
 	file "$file" | grep -q text || { ditto skipping "${file#./}"; continue; }
-	unset blink
 	[ $T ] && targetfile=$target || targetfile="${target}/${file#./}"
 	while : ;do
 		[ $FILTER ] && [ "$file" -ot $FILTER ] && break
 		[ $S ] && clear
 		file="${file#./}"
-		[ $title ] || { ditto -t diff "$src/$regex && $target" >>$LOG; title=true; }
-		[ -e "${targetfile}" ] || { ditto ERROR missing "${targetfile}" >>$LOG; break; }
-		if ! diff --brief $w "${file}" "${targetfile}" >/dev/null 2>&1 ;then
-			[ $S ] || clear
-			ditto diff "${file}"
-			kakdiff "${file}" "${targetfile}"
-			[ $? -eq 1 ] && blink=${BLINK} || break
-		else
-			ditto match "${file}"
-			[ $S ] && sleep $delay
-			break
-		fi
+		[ $title ] || { ditto -t $(basename $0) "$src/$regex  ->  $target" >>$LOG; title=true; }
+		[ -e "${targetfile}" ] || { ditto ERROR notfound "${targetfile}" >>$LOG; break; }
+		kakdiff "${file}" "${targetfile}"
+		case $? in
+			0 ) ditto match "${file}"; [ $S ] && sleep $delay; break ;;
+			1 ) break ;;
+			2 ) ;;  # SEE: kakdiff
+		esac
 	done
 done 3< $FILES
+
+[ -e $LOG ] && cat $LOG | pager
 
 # kak: filetype=sh
