accessibility conversion to hardtabs

diff --git a/bin/bin/functions/X11/functions/dmenu/econvert b/bin/bin/functions/X11/functions/dmenu/econvert
--- a/bin/bin/functions/X11/functions/dmenu/econvert
+++ b/bin/bin/functions/X11/functions/dmenu/econvert
@@ -22,31 +22,36 @@ em_linespace=0,1.25
 
 # override device/cloud transfer and create kindle/kobo file
 case $1 in
-  azw3    ) format=$1; option=${option:-default}; em_indent=${em_indent#*,}; library=true; shift ;;  # library update
-  epub    ) format=$1; option=${option:-default}; em_indent=${em_indent%,*}; library=true; shift ;;  # epub output hack
-  reformat) format=$1; option=${option:-default}; em_indent=${em_indent%,*}; library=true; shift ;;  # epub output hack
+	azw3    ) format=$1; option=${option:-default}; em_indent=${em_indent#*,}; library=true; shift ;;  # library update
+	epub    ) format=$1; option=${option:-default}; em_indent=${em_indent%,*}; library=true; shift ;;  # epub output hack
+	reformat) format=$1; option=${option:-default}; em_indent=${em_indent%,*}; library=true; shift ;;  # epub output hack
 esac
 
 # override left justification
 case "$1" in
-  ''      ) ;;
-  default ) option=default;  shift ;;
-  justify ) option=justify;  shift ;;
-  noindent) option=noindent; shift ;;  # retain poetry formatting
-  poetry  ) option=noindent; shift ;;  # retain poetry formatting
-  all     ) option=all;      shift ;;
-  *       ) [ -e "$1" ] || { find . -iname "$1" | grep -q '[.]' || usage; } ;;
+	''      ) ;;
+	default ) option=default;  shift ;;
+	justify ) option=justify;  shift ;;
+	noindent) option=noindent; shift ;;  # retain poetry formatting
+	poetry  ) option=noindent; shift ;;  # retain poetry formatting
+	all     ) option=all;      shift ;;
+	*       ) [ -e "$1" ] || { find . -iname "$1" | grep -q '[.]' || usage; } ;;
 esac
 
 # <regex> autoconvert epubs to awz3
 case "$format" in
-  azw3    ) [ "$1"    ] || { find . -iname '*epub'             -exec dmenu econvert azw3 $option {} \; ; exit; }
-            [ -e "$1" ] || { find . -iname "$1"                -exec dmenu econvert azw3 $option {} \; ; exit; } ;;
-  epub    ) [ "$1"    ] || { find . -iname '*azw3'             -exec dmenu econvert epub $option {} \; ; exit; }
-            [ -e "$1" ] || { find . -iname "$1"                -exec dmenu econvert epub $option {} \; ; exit; } ;;
-  reformat) [ "$1"    ] || { find . -iregex '.*\(azw3\|epub\)' -exec dmenu econvert reformat $option {} \; ; exit; }
-            [ -e "$1" ] || { find . -iname "$1"                -exec dmenu econvert reformat $option {} \; ; exit; }
-            format=${1##*\.}; reformat=true ;;  # for re-tweaking converted ebooks
+	azw3    )
+		[ "$1"    ] || { find . -iname '*epub'             -exec dmenu econvert azw3 $option {} \; ; exit; }
+		[ -e "$1" ] || { find . -iname "$1"                -exec dmenu econvert azw3 $option {} \; ; exit; } ;;
+
+	epub    )
+		[ "$1"    ] || { find . -iname '*azw3'             -exec dmenu econvert epub $option {} \; ; exit; }
+		[ -e "$1" ] || { find . -iname "$1"                -exec dmenu econvert epub $option {} \; ; exit; } ;;
+
+	reformat)
+		[ "$1"    ] || { find . -iregex '.*\(azw3\|epub\)' -exec dmenu econvert reformat $option {} \; ; exit; }
+		[ -e "$1" ] || { find . -iname "$1"                -exec dmenu econvert reformat $option {} \; ; exit; }
+		format=${1##*\.}; reformat=true ;;  # for re-tweaking converted ebooks
 esac
 
 file=$1
@@ -59,7 +64,7 @@ title=${name% - *}
 
 # kindle update via email
 email() {
-  cat - <<END
+	cat - <<END
 Content-Type: multipart/mixed; boundary="$boundary"
 MIME-Version: 1.0
 Subject: $title
@@ -80,8 +85,8 @@ Content-Transfer-Encoding: base64
 Content-Disposition: attachment; filename="${mobi##*/}"
 
 END
-                base64 "$mobi"
-                cat - <<END
+	base64 "$mobi"
+	cat - <<END
 
 --$boundary--
 END
@@ -99,10 +104,10 @@ output=ebook-convert:ebook  # flatpak ebook-convert cannot not output to path(?)
 justify=left
 em_linespace=${em_linespace%,*}
 case $option in
-  default ) ;;
-  noindent) em_indent=0; em_linespace=${em_linespace#*,} ;;
-  justify ) justify=justify ;;
-  all     ) unset indent; em_linespace=${em_linespace#*,}; justify=justify ;;
+	default ) ;;
+	noindent) em_indent=0; em_linespace=${em_linespace#*,} ;;
+	justify ) justify=justify ;;
+	all     ) unset indent; em_linespace=${em_linespace#*,}; justify=justify ;;
 esac
 
 notify low "$title" "Converting to $format..\n--change-justification="$justify" $indent"
@@ -111,37 +116,37 @@ ditto $format "$file"
 # ebook-convert "$file" "${output%.*}.epub"  # test image
 # convert even .azw3 to inject folder title and author
 alpine && EBOOK_CONVERT='flatpak run --command="ebook-convert" --user com.calibre_ebook.calibre' || EBOOK_CONVERT=ebook-convert
-eval $EBOOK_CONVERT \"$file\" \"${output%.*}.$format\"                                           \
-                    $([ $reformat ] && echo || echo "--title=\"$title\" --authors=\"$author\"")  \
-                    --change-justification=\"$justify\"                                          \
-                    --remove-paragraph-spacing --remove-paragraph-spacing-indent-size=$em_indent \
-                    --insert-blank-line --insert-blank-line-size=$em_linespace                   \
-                    --filter-css=\'font-family, float\'                                          \
-                    >/tmp/ebook-convert.log 2>/dev/null || exit  # suppress plugin initialization warnings
+eval $EBOOK_CONVERT \"$file\" \"${output%.*}.$format\"                          \
+	$([ $reformat ] && echo || echo "--title=\"$title\" --authors=\"$author\"")  \
+	--change-justification=\"$justify\"                                          \
+	--remove-paragraph-spacing --remove-paragraph-spacing-indent-size=$em_indent \
+	--insert-blank-line --insert-blank-line-size=$em_linespace                   \
+	--filter-css=\'font-family, float\'                                          \
+	>/tmp/ebook-convert.log 2>/dev/null || exit  # suppress plugin initialization warnings
 
 # ........................................................................ Write
 
 # usb, cloud or library update?
 if [ $library ] ;then
-  # find /tmp -maxdepth 1 -name "*$format" -exec mv -f "{}" "$folder" \;
-  mv -f "${output%.*}.$format" "${file%.*}.$format"  # alpine flatpak
-  notify low "$title" "$folder"
+	# find /tmp -maxdepth 1 -name "*$format" -exec mv -f "{}" "$folder" \;
+	mv -f "${output%.*}.$format" "${file%.*}.$format"  # alpine flatpak
+	notify low "$title" "$folder"
 elif [ -d $KINDLE ] ;then
-  find $KINDLE -maxdepth 1 -wholename "${file% - *}*.sdr" -exec rm -rf "{}" \;  # cleanup dangling sdr files
-  find /tmp -maxdepth 1 -name "*$format" -exec rm -rf "$KINDLE${file% - *}*.sdr" \; -exec mv -f "{}" $KINDLE \;
-  notify low "$title" "$KINDLE"
-  sync
+	find $KINDLE -maxdepth 1 -wholename "${file% - *}*.sdr" -exec rm -rf "{}" \;  # cleanup dangling sdr files
+	find /tmp -maxdepth 1 -name "*$format" -exec rm -rf "$KINDLE${file% - *}*.sdr" \; -exec mv -f "{}" $KINDLE \;
+	notify low "$title" "$KINDLE"
+	sync
 elif [ $format = mobi ] ;then
-  mobi=$(find /tmp -maxdepth 1 -name "*$format")
-  address=$(echo | mhistory kindle | rmenu 'Address <@kindle.com>') || break
-  echo "$address" | grep -q '\@' || address=${address}@kindle.com
-  mhistory kindle $address
-  account=$(grep $USER /etc/aliases | cut -d' ' -f2)
-  boundary="=-=-=-=-=-=-=-=-=-=$(od -An -N9 -i /dev/random | sed 's/ //g' | cut -b1-19)=-="
-  email | /usr/local/bin/msmtp-enqueue.sh -t &
-  notify low "$title" "$address"
+	mobi=$(find /tmp -maxdepth 1 -name "*$format")
+	address=$(echo | mhistory kindle | rmenu 'Address <@kindle.com>') || break
+	echo "$address" | grep -q '\@' || address=${address}@kindle.com
+	mhistory kindle $address
+	account=$(grep $USER /etc/aliases | cut -d' ' -f2)
+	boundary="=-=-=-=-=-=-=-=-=-=$(od -An -N9 -i /dev/random | sed 's/ //g' | cut -b1-19)=-="
+	email | /usr/local/bin/msmtp-enqueue.sh -t &
+	notify low "$title" "$address"
 else
-  ditto epub "$(find /tmp -maxdepth 1 -name "*$format")"
+	ditto epub "$(find /tmp -maxdepth 1 -name "*$format")"
 fi
 
 # vim: set ft=sh: #
diff --git a/bin/bin/functions/X11/functions/dmenu/wiki b/bin/bin/functions/X11/functions/dmenu/wiki
--- a/bin/bin/functions/X11/functions/dmenu/wiki
+++ b/bin/bin/functions/X11/functions/dmenu/wiki
@@ -18,55 +18,56 @@ dirs()  { find -L $WIKIS -maxdepth 2 -type d | sort | exclude 'mail|templates|xr
 
 # recover full pathname
 expand() {
-  [ -e "$WIKIS/$1.wiki" ] || return 1
-  echo "$WIKIS/$1.wiki"
-  return 0
+	[ -e "$WIKIS/$1.wiki" ] || return 1
+	echo "$WIKIS/$1.wiki"
+	return 0
 }
 
 # apostrophes in filename cannot be handled by duochrome statusline..
 apostrophe_check() {
-  # so substitute a linked file with carets
-  [ "${file%\'*}" = "$file" ] || { link=/tmp/$(echo "${file##*/}" | tr \' ^); ln -sf "$file" "$link"; file=$link; }
+	# so substitute a linked file with carets
+	[ "${file%\'*}" = "$file" ] || { link=/tmp/$(echo "${file##*/}" | tr \' ^); ln -sf "$file" "$link"; file=$link; }
 }
 
 add() {
-  wiki=$(dirs | rmenu "$prompt" -no-custom) || exit
-  [ $1 ] || { [ $prompt = Diary ] && title=$(date '+%Y-%m-%d'); } || title=$(echo | rmenu 'Title') || exit
-  mhistory wiki$1 "$title^$SEP $wiki"
-  file=$WIKIS/$wiki/$title.wiki
-  # prepend h1 title
-  echo "# $title\n\n" >$file
-  apostrophe_check
-  v -c ':normal! G' "$file"
+	wiki=$(dirs | rmenu "$prompt" -no-custom) || exit
+	[ $1 ] || { [ $prompt = Diary ] && title=$(date '+%Y-%m-%d'); } || title=$(echo | rmenu 'Title') || exit
+	mhistory wiki$1 "$title^$SEP $wiki"
+	file=$WIKIS/$wiki/$title.wiki
+	# prepend h1 title
+	echo "# $title\n\n" >$file
+	apostrophe_check
+	v -c ':normal! G' "$file"
 }
 
 wiki() {
-  mhistory wiki$1 "$(echo $file | sed "s/ *$SEP/^$SEP/")"
-  file=$(echo $file | sed -r "s,(.*)  *$SEP  *(.*),\2/\1,")
-  if expand "$file" >/dev/null ;then
-    file="$(expand "$file")"
-    apostrophe_check
-    v "$file"
-    # history file cleanup usually precedes impending edit
-    # expand "$file" | grep -q dmenu/.history && { pwait "vim.*"$(expand "$file")""; dmenu edit; }
-  else
-    error=": ${file##*/} ∉ ${file%/*}"
-    sed -i "\|${file##*/}.$SEP ${file%/*}$|d" $HISTORY/wiki
-    file=${file##*/}
-    return 1
-  fi
+	mhistory wiki$1 "$(echo $file | sed "s/ *$SEP/^$SEP/")"
+	file=$(echo $file | sed -r "s,(.*)  *$SEP  *(.*),\2/\1,")
+	if expand "$file" >/dev/null ;then
+		file="$(expand "$file")"
+		apostrophe_check
+		v "$file"
+		# history file cleanup usually precedes impending edit
+		# expand "$file" | grep -q dmenu/.history && { pwait "vim.*"$(expand "$file")""; dmenu edit; }
+	else
+		error=": ${file##*/} ∉ ${file%/*}"
+		sed -i "\|${file##*/}.$SEP ${file%/*}$|d" $HISTORY/wiki
+		file=${file##*/}
+		return 1
+	fi
 }
 
 while : ;do
-  file=$(files | sed "s,$WIKIS/,," | sed -r "s,(.*)/([^/]*)$,\2^$SEP \1," | sort | mhistory wiki$1 | column -s^ -t |
-      sed  "2i$(X $EDIT)$menu" | rmenu "Edit $prompt$error" -no-custom) || exit
+	file=$(files | sed "s,$WIKIS/,," | sed -r "s,(.*)/([^/]*)$,\2^$SEP \1," \
+		| sort | mhistory wiki$1 | column -s^ -t | sed  "2i$(X $EDIT)$menu"  \
+		| rmenu "Edit $prompt$error" -no-custom) || exit
 
-  case ${file#$(X)} in
-    "$DIARY") exec dmenu wiki diary ;;
-    "$EDIT" ) add ;;
-    *       ) wiki || continue ;;
-  esac
-  break
+	case ${file#$(X)} in
+		"$DIARY") exec dmenu wiki diary ;;
+		"$EDIT" ) add ;;
+		*       ) wiki || continue ;;
+	esac
+	break
 done
 
 # vim: set ft=sh: #
diff --git a/bin/bin/functions/X11/x b/bin/bin/functions/X11/x
--- a/bin/bin/functions/X11/x
+++ b/bin/bin/functions/X11/x
@@ -23,55 +23,58 @@ font=emboss
 
 # see .xinitrc
 case $1 in
-  abort | halt | stop ) [ -e $BOOTWM ] && ditto user_login 'canceling startx'; rm -f $BOOTWM; exit ;;  # boot intercept shortcut
-  ''  ) ;;
-  2b* ) echo 2bwm >$WM ;;
-  aw* ) echo awesome >$WM ;;
-  bs* ) echo bspwm >$WM ;;
-  bu* ) echo budgie >$WM ;;
-  ci* ) echo cinnamon >$WM ;;
-  dw* ) echo dwm >$WM ;;
-  gn* ) echo gnome >$WM ;;
-  go* ) echo goomwwm >$WM ;;
-  gu* ) echo guile >$WM ;;
-  he* ) echo herbstluftwm >$WM ;;
-  i3  ) echo i3 >$WM ;;
-  kde ) echo kde >$WM ;;
-  le* ) echo leftwm >$WM ;;
-  lxd*) echo lxde >$WM ;;
-  lxq*) echo lxqt >$WM ;;
-  ma* ) echo mate >$WM ;;
-  no* ) echo notion >$WM ;;
-  op* ) echo openbox >$WM ;;
-  rat*) echo ratpoison >$WM ;;
-  raz*) echo razor-qt >$WM ;;
-  sp* ) echo spectrwm >$WM ;;
-  st* ) echo stumpwm >$WM ;;
-  su* ) echo subtle >$WM ;;
-  sh* ) echo shell >$WM ;;
-  wi* ) echo windowchef >$WM ;;
-  wmi*) echo wmii >$WM ;;
-  wmu*) echo wmutils >$WM ;;
-  wt* ) echo wtftw >$WM ;;
-  xf* ) echo xfce4 >$WM ;;
-  xm* ) echo xmonad >$WM ;;
-  *   ) usage ;;
+	abort | halt | stop ) [ -e $BOOTWM ] && ditto user_login 'canceling startx'; rm -f $BOOTWM; exit ;;  # boot intercept shortcut
+	''  ) ;;
+	2b* ) echo 2bwm >$WM ;;
+	aw* ) echo awesome >$WM ;;
+	bs* ) echo bspwm >$WM ;;
+	bu* ) echo budgie >$WM ;;
+	ci* ) echo cinnamon >$WM ;;
+	dw* ) echo dwm >$WM ;;
+	gn* ) echo gnome >$WM ;;
+	go* ) echo goomwwm >$WM ;;
+	gu* ) echo guile >$WM ;;
+	he* ) echo herbstluftwm >$WM ;;
+	i3  ) echo i3 >$WM ;;
+	kde ) echo kde >$WM ;;
+	le* ) echo leftwm >$WM ;;
+	lxd*) echo lxde >$WM ;;
+	lxq*) echo lxqt >$WM ;;
+	ma* ) echo mate >$WM ;;
+	no* ) echo notion >$WM ;;
+	op* ) echo openbox >$WM ;;
+	rat*) echo ratpoison >$WM ;;
+	raz*) echo razor-qt >$WM ;;
+	sp* ) echo spectrwm >$WM ;;
+	st* ) echo stumpwm >$WM ;;
+	su* ) echo subtle >$WM ;;
+	sh* ) echo shell >$WM ;;
+	wi* ) echo windowchef >$WM ;;
+	wmi*) echo wmii >$WM ;;
+	wmu*) echo wmutils >$WM ;;
+	wt* ) echo wtftw >$WM ;;
+	xf* ) echo xfce4 >$WM ;;
+	xm* ) echo xmonad >$WM ;;
+	*   ) usage ;;
 esac
 
 # .......................................................................... NFS
 
 # for xorg session restricted nfs: $SESSION/nfs
 nfs() {
-  case $1 in
-    mount ) if [ ! -d /net/depot/dotfiles ] ;then
-              ditto nfs 'mount..' 
-              grep -q "^$HOME/Maildir" /etc/fstab && sudo mount -v $HOME/Maildir 
-              sudo mount -v /net 
-            fi ;;
-    umount) ditto nfs 'umount..' 
-            sudo umount -v /net 
-            grep -q "^$HOME/Maildir" /etc/fstab && sudo umount -v $HOME/Maildir ;;
-  esac
+	case $1 in
+		mount )
+			if [ ! -d /net/depot/dotfiles ] ;then
+				ditto nfs 'mount..' 
+				grep -q "^$HOME/Maildir" /etc/fstab && sudo mount -v $HOME/Maildir 
+				sudo mount -v /net 
+			fi ;;
+
+		umount)
+			ditto nfs 'umount..' 
+			sudo umount -v /net 
+			grep -q "^$HOME/Maildir" /etc/fstab && sudo umount -v $HOME/Maildir ;;
+	esac
 }
 
 NFSLOG=/tmp/.xinit:nfs.log
@@ -84,62 +87,62 @@ nfs mount
 
 # start X11 from init console
 if console ;then
-  wm=$(cat $WM)
-  [ ${#wm} -le 12 ] && extra=' '  # emboss spacing
-  [ $font = emboss ] && seat=$(echo $wm | sed -r "s/(.)/\1 $extra/g; s/ *$//") || seat=$wm
-  [ $(cat $SEAT) -lt 240 ] && seat="$(echo $seat | cut -c -24)"  # assumes display width jump from 1920 to 1366
-  void && toilet -F gay -f $font "$seat" || { echo $BLACK; figlet -t -S -f lean "$seat"; echo $NOCOLOR; }
-  [ $wm = shell ] && exit  # escape to shell prompt
+	wm=$(cat $WM)
+	[ ${#wm} -le 12 ] && extra=' '  # emboss spacing
+	[ $font = emboss ] && seat=$(echo $wm | sed -r "s/(.)/\1 $extra/g; s/ *$//") || seat=$wm
+	[ $(cat $SEAT) -lt 240 ] && seat="$(echo $seat | cut -c -24)"  # assumes display width jump from 1920 to 1366
+	void && toilet -F gay -f $font "$seat" || { echo $BLACK; figlet -t -S -f lean "$seat"; echo $NOCOLOR; }
+	[ $wm = shell ] && exit  # escape to shell prompt
 
-  pstat startx && exit
-  cpu arm && { tmout ifyes 'sync with watchman' && wsync || wsync -s; }
-  # mount any dangling nfs shares
-  # sudo mount -a
-  startx -- 2>/tmp/startx:x.log
+	pstat startx && exit
+	cpu arm && { tmout ifyes 'sync with watchman' && wsync || wsync -s; }
+	# mount any dangling nfs shares
+	# sudo mount -a
+	startx -- 2>/tmp/startx:x.log
 
-  # session specific clean up
-  pkill -KILL $wm
-  case $wm in
-    2b* ) ;;
-    aw* ) ;;
-    bs* ) ;;
-    bu* ) ;;
-    ci* ) ;;
-    dw* ) ;;
-    gn* ) ;;
-    go* ) ;;
-    gu* ) ;;
-    he* ) ;;
-    i3  ) ;;
-    kde ) ;;
-    le* ) ;;
-    lxd*) ;;
-    lxq*) ;;
-    ma* ) ;;
-    no* ) ;;
-    op* ) ;;
-    rat*) ;;
-    raz*) ;;
-    sp* ) ;;
-    st* ) ;;
-    su* ) ;;
-    sh* ) ;;
-    wi* ) ;;
-    wmi*) ;;
-    wmu*) ;;
-    wt* ) ;;
-    xf* ) ;;
-    xm* ) ;;
-  esac
+	# session specific clean up
+	pkill -KILL $wm
+	case $wm in
+		2b* ) ;;
+		aw* ) ;;
+		bs* ) ;;
+		bu* ) ;;
+		ci* ) ;;
+		dw* ) ;;
+		gn* ) ;;
+		go* ) ;;
+		gu* ) ;;
+		he* ) ;;
+		i3  ) ;;
+		kde ) ;;
+		le* ) ;;
+		lxd*) ;;
+		lxq*) ;;
+		ma* ) ;;
+		no* ) ;;
+		op* ) ;;
+		rat*) ;;
+		raz*) ;;
+		sp* ) ;;
+		st* ) ;;
+		su* ) ;;
+		sh* ) ;;
+		wi* ) ;;
+		wmi*) ;;
+		wmu*) ;;
+		wt* ) ;;
+		xf* ) ;;
+		xm* ) ;;
+	esac
 
-  # rare dangling instances..
-  killall -KILL qutebrowser 2>/dev/null
-  killall -KILL weechat 2>/dev/null 
+	# rare dangling instances..
+	killall -KILL qutebrowser 2>/dev/null
+	killall -KILL weechat 2>/dev/null 
 
-  cpu arm && { pstat syncthing || { tmout ifno 'sync with syncthing' || wsync -s; } }
+	cpu arm && { pstat syncthing || { tmout ifno 'sync with syncthing' || wsync -s; } }
 else
-  # already in X11 session
-  ditto 'window manager' "$(cat $WM) (next X session)"
+	# already in X11 session
+	ditto 'window manager' "$(cat $WM) (next X session)"
 fi
 
 # vim: set ft=sh: #
diff --git a/bin/bin/functions/dev/dotfiles b/bin/bin/functions/dev/dotfiles
--- a/bin/bin/functions/dev/dotfiles
+++ b/bin/bin/functions/dev/dotfiles
@@ -9,13 +9,13 @@
 # .......................................................................... Git
 
 usage() {
-  echo "$(basename $0) [<stowdir>] add [-f] <package>[/<filespec>]* | rm <filespec>
+	echo "$(basename $0) [<stowdir>] add [-f] <package>[/<filespec>]* | rm <filespec>
 $(basename $0) amend|comment [<comment>] | redo|undo
 $(basename $0) init [<comment>] | bulk <comment> | sync
 $(basename $0) dry-run | folders|ignore | list | log
 
 see $DOTFILES" | usage:
-  exit 1
+	exit 1
 }
 
 # list of folders under stow root
@@ -38,65 +38,65 @@ find . -name '*.syncthing.hsts.tmp' -exec rm {} \;
 sudo find . -name '.uuid' -exec rm {} \;
 
 init() {
-  git init
-  git add README.md
-  git commit --message="refresh commit"
-  git branch -M main
-  git remote add origin git+ssh://git@github.com/sdothum/dotfiles.git
-  git push -u origin main
-  git remote set-url origin git+ssh://git@github.com/sdothum/dotfiles.git
+	git init
+	git add README.md
+	git commit --message="refresh commit"
+	git branch -M main
+	git remote add origin git+ssh://git@github.com/sdothum/dotfiles.git
+	git push -u origin main
+	git remote set-url origin git+ssh://git@github.com/sdothum/dotfiles.git
 
-  dotfiles bulk "$DESC"
+	dotfiles bulk "$DESC"
 }
 
 commit() {
-  echo
-  git commit --message="$DESC"
-  git push --force --set-upstream origin main
-  COMMIT=true  # see bulk
+	echo
+	git commit --message="$DESC"
+	git push --force --set-upstream origin main
+	COMMIT=true  # see bulk
 }
 
 pending() {
-  echo $pending | sed -r "s/' (add|remove) '/\n\1 /g; s/^(add|remove) '/\1 /; s/'$//" | while read pending ;do
-    action=$(echo $pending | cut -d' ' -f1)
-    [ $action = remove ] && info=INFO || unset info
-    ditto $info $action "$(echo $pending | cut -d' ' -f2-)"
-  done
-  if [ $NOPROMPT ] ;then
-    commit
-  else
-    printf "commit? [Abort]/comment.. : ${WHITE}"
-    read DESC
-    printf "${NOCOLOR}"
-    [ "$DESC" ] || exit 1
-    ifyes "Push: $DESC" && commit
-  fi
+	echo $pending | sed -r "s/' (add|remove) '/\n\1 /g; s/^(add|remove) '/\1 /; s/'$//" | while read pending ;do
+		action=$(echo $pending | cut -d' ' -f1)
+		[ $action = remove ] && info=INFO || unset info
+		ditto $info $action "$(echo $pending | cut -d' ' -f2-)"
+	done
+	if [ $NOPROMPT ] ;then
+		commit
+	else
+		printf "commit? [Abort]/comment.. : ${WHITE}"
+		read DESC
+		printf "${NOCOLOR}"
+		[ "$DESC" ] || exit 1
+		ifyes "Push: $DESC" && commit
+	fi
 }
 
 # add !**<path> to .gitignore for any <path> force warnings
 add() {
-  file="$STOW/$1"
-  if [ $(ls -Alr $file | wc -l) -gt 0 ] ;then
-    pending=$(git add -v $force "$file" )
-  else
-    ditto WARNING notfound "$file"
-  fi
-  [ "$pending" ] && pending
+	file="$STOW/$1"
+	if [ $(ls -Alr $file | wc -l) -gt 0 ] ;then
+		pending=$(git add -v $force "$file" )
+	else
+		ditto WARNING notfound "$file"
+	fi
+	[ "$pending" ] && pending
 }
 
 rm() {
-  if [ $1 ] ;then
-    DESC=$@
-    git rm -r --cached $DESC
-    git commit --message="Remove directory \"$DESC\""
-    git push origin main
-  fi
+	if [ $1 ] ;then
+		DESC=$@
+		git rm -r --cached $DESC
+		git commit --message="Remove directory \"$DESC\""
+		git push origin main
+	fi
 }
 
 sync() {
-  for i in * ;do
-    ifno "sync $i" || dotfiles add $i
-  done
+	for i in * ;do
+		ifno "sync $i" || dotfiles add $i
+	done
 }
 
 # any updates to push?
@@ -111,34 +111,38 @@ status()   { underline; dotfiles dry-run; }
 # $@ substitution within complex expressions is more predictably handled by var substitution
 unset pending
 case $1 in
-  help   ) usage ;;
-  ''     ) dotfiles dry-run; grep -q "$UPTODATE" $MESSAGES || { ifyes "update repo" && repo; status; } ;;
-  bulk   ) NOPROMPT=true; DESC="${2:-bulk commit}"; repo; [ $COMMIT ] && status; ;;
+	help   ) usage ;;
+	''     ) dotfiles dry-run; grep -q "$UPTODATE" $MESSAGES || { ifyes "update repo" && repo; status; } ;;
+	bulk   ) NOPROMPT=true; DESC="${2:-bulk commit}"; repo; [ $COMMIT ] && status; ;;
 
-  add    ) shift; [ "$1" = '-f' ] && { force=-f; shift; }
-           while [ "$1" ] ;do add "$1"; shift ;done ;;  # handle filename spaces
-  
-  amend    |\
-  comment) shift; DESC=$@
-           [ "$DESC" ] && git commit --amend --no-edit --message="$DESC" || git commit --amend ;;
-  
-  dry*   ) git commit --dry-run >$MESSAGES
-           cat $MESSAGES | print ;;
+	add    )
+		shift; [ "$1" = '-f' ] && { force=-f; shift; }
+		while [ "$1" ] ;do add "$1"; shift ;done ;;  # handle filename spaces
+	
+	amend  |\
+	comment)
+		shift; DESC=$@
+		[ "$DESC" ] && git commit --amend --no-edit --message="$DESC" || git commit --amend ;;
+	
+	dry*   )
+		git commit --dry-run >$MESSAGES
+		cat $MESSAGES | print ;;
 
-  folder*) vim -g $DOTFILES .gitignore $(messages) ;;
-  ignore ) vim -g .gitignore $DOTFILES $(messages) ;;
-  init   ) DESC="${2:-fresh commit}"; init ;;
-  list   ) git log --pretty=format:"%h - %an, %ar : %s" ;;
-  log    ) git log | less ;;
-  
-  redo     |\
-  undo   ) git reset --soft HEAD~
-           dotfiles ;;
-  
-  reset  ) git reset ;;
-  rm     ) shift; rm $@ ;;
-  sync   ) sync ;;
-  *      ) add $@ ;;
+	folder*) vim -g $DOTFILES .gitignore $(messages) ;;
+	ignore ) vim -g .gitignore $DOTFILES $(messages) ;;
+	init   ) DESC="${2:-fresh commit}"; init ;;
+	list   ) git log --pretty=format:"%h - %an, %ar : %s" ;;
+	log    ) git log | less ;;
+	
+	redo   |\
+	undo   )
+		git reset --soft HEAD~
+		dotfiles ;;
+	
+	reset  ) git reset ;;
+	rm     ) shift; rm $@ ;;
+	sync   ) sync ;;
+	*      ) add $@ ;;
 esac
 
 # vim: set ft=sh: #
diff --git a/bin/bin/functions/log/ditto b/bin/bin/functions/log/ditto
--- a/bin/bin/functions/log/ditto
+++ b/bin/bin/functions/log/ditto
@@ -9,11 +9,11 @@
 # ..................................................................... Annotate
 
 usage() {
-  echo "$(basename $0) [ ERROR | WARNING | INFO ] @ *<desc> | [-t | <desc> | -- | ..]* <message>
+	echo "$(basename $0) [ ERROR | WARNING | INFO ] @ *<desc> | [-t | <desc> | -- | ..]* <message>
 where, default <desc> -> "note"
 <                  -- -> line separator
 <                  .. -> justify leader" | usage:
-  exit 1
+	exit 1
 }
 
 [ "$1" ] || usage
@@ -23,37 +23,37 @@ ATTCOLOR=${TURQUOISE}
 MSGCOLOR=${green}
 
 while [ "$1" ] ;do
-  case $1 in
-    ERR*) ATTCOLOR=${RED}; MSGCOLOR=${brown}   ;;
-    WAR*) ATTCOLOR=${BROWN} MSGCOLOR=${orange} ;;
-    INF*) ATTCOLOR=${WHITE} MSGCOLOR=${cyan} ;;
-    @   ) [ "$2" ] || usage; desc=$2; message=' ';     shift ;;
-    @*  ) [ "$2" ] && usage; desc=${1#@}; message=' '        ;;
-    -t  ) timestamp="${WHITE}$(date "+%-H %M'%S\" ")"                ;;
-    ..  ) [ "$2" ] || usage; justify=true; message=$2; shift ;;
-    --  ) separator=true ;;
-    *   ) [ "$message" ] && desc=$message; message=$1 ;;
-  esac
-  shift
+	case $1 in
+		ERR*) ATTCOLOR=${RED}; MSGCOLOR=${brown}   ;;
+		WAR*) ATTCOLOR=${BROWN} MSGCOLOR=${orange} ;;
+		INF*) ATTCOLOR=${WHITE} MSGCOLOR=${cyan} ;;
+		@   ) [ "$2" ] || usage; desc=$2; message=' ';     shift ;;
+		@*  ) [ "$2" ] && usage; desc=${1#@}; message=' '        ;;
+		-t  ) timestamp="${WHITE}$(date "+%-H %M'%S\" ")"                ;;
+		..  ) [ "$2" ] || usage; justify=true; message=$2; shift ;;
+		--  ) separator=true ;;
+		*   ) [ "$message" ] && desc=$message; message=$1 ;;
+	esac
+	shift
 done
 # [ "$desc" = "$message" ] && usage
 [ "$desc" ] || desc=note
 
 justify() {
-  while read line ;do
-    # indent=$(echo "$(tput cols) - $(echo $line | wc -L) - 3" | bc)
-    indent=$(( $(tput cols) - $(echo $line | wc -L) - 3 ))
-    [ $indent -gt 0 ] && leader=$(head -c $indent </dev/zero | tr '\0' "$leader")
-    log "${ATTCOLOR}@ $leader ${MSGCOLOR}$line${NOCOLOR}"
-    leader=' '
-  done
+	while read line ;do
+		# indent=$(echo "$(tput cols) - $(echo $line | wc -L) - 3" | bc)
+		indent=$(( $(tput cols) - $(echo $line | wc -L) - 3 ))
+		[ $indent -gt 0 ] && leader=$(head -c $indent </dev/zero | tr '\0' "$leader")
+		log "${ATTCOLOR}@ $leader ${MSGCOLOR}$line${NOCOLOR}"
+		leader=' '
+	done
 }
 
 annotate() {
-  [ $separator ] && drawline $leader
-  while read line ;do
-    log "$timestamp${ATTCOLOR}@${desc} ${MSGCOLOR}$line${NOCOLOR}"
-  done
+	[ $separator ] && drawline $leader
+	while read line ;do
+		log "$timestamp${ATTCOLOR}@${desc} ${MSGCOLOR}$line${NOCOLOR}"
+	done
 }
 
 echo "$message" | sed '/^$/d' | { [ $justify ] && justify || annotate; }  # omit blank lines
diff --git a/bin/bin/functions/office/epubcheck b/bin/bin/functions/office/epubcheck
--- a/bin/bin/functions/office/epubcheck
+++ b/bin/bin/functions/office/epubcheck
@@ -12,16 +12,16 @@ CATLG=/tmp/epubcheck:catlg
 LOG=/tmp/epubcheck.log
 
 case $1 in
-  ''   ) usage ;;
-  *epub) echo $1 >$CATLG ;;
-  *    ) find "$1" -name '*epub' >$CATLG 2>/dev/null || usage ;;
+	''   ) usage ;;
+	*epub) echo $1 >$CATLG ;;
+	*    ) find "$1" -name '*epub' >$CATLG 2>/dev/null || usage ;;
 esac
 
 while read file <&3 ;do
-  
-  java -jar $HOME/.local/bin/epubcheck.jar -v 2.0 "$file" 2>$LOG >/dev/null
-  grep -q -E '(FATAL|ERROR)' $LOG || { ditto epubcheck "$file"; continue; }
-  ditto ERROR epubcheck "$file ${NOCOLOR}$(grep -E '(FATAL|ERROR)' $LOG | cut -d: -f1 | sort -u | sed 's/ERROR(RSC-/E-/; s/)//'| tr '\n' ' ')"
+	
+	java -jar $HOME/.local/bin/epubcheck.jar -v 2.0 "$file" 2>$LOG >/dev/null
+	grep -q -E '(FATAL|ERROR)' $LOG || { ditto epubcheck "$file"; continue; }
+	ditto ERROR epubcheck "$file ${NOCOLOR}$(grep -E '(FATAL|ERROR)' $LOG | cut -d: -f1 | sort -u | sed 's/ERROR(RSC-/E-/; s/)//'| tr '\n' ' ')"
 done 3< $CATLG
 
 # vim: set ft=sh: #
diff --git a/bin/bin/functions/package/arch/trackpkg b/bin/bin/functions/package/arch/trackpkg
--- a/bin/bin/functions/package/arch/trackpkg
+++ b/bin/bin/functions/package/arch/trackpkg
@@ -18,32 +18,32 @@ wrappaur=$(aurwrapper)
 [ -e $conf ] || touch $conf
 
 add_pkg() {
-  for i in $@ ;do
-    pkg=$(am $i)
-    if [ $(echo $pkg | wc -l) -eq 2 ] ;then
-      echo "$i:$(echo $pkg | head -1 | sed 's/ (.*)//')" >>$conf
-      sort -uo $conf $conf
-    else
-      ditto ERROR package "\"$i\" not found"
-    fi
-  done
-  trackpkg
+	for i in $@ ;do
+		pkg=$(am $i)
+		if [ $(echo $pkg | wc -l) -eq 2 ] ;then
+			echo "$i:$(echo $pkg | head -1 | sed 's/ (.*)//')" >>$conf
+			sort -uo $conf $conf
+		else
+			ditto ERROR package "\"$i\" not found"
+		fi
+	done
+	trackpkg
 }
 
 del_pkg() {
-  ifyes "no longer track:  $(grep "^$@" $conf | cut -d: -f2)" &&
-    for i in $@ ;do sed -i "/^$i/d" $conf ;done
-  trackpkg
+	ifyes "no longer track:  $(grep "^$@" $conf | cut -d: -f2)" &&
+		for i in $@ ;do sed -i "/^$i/d" $conf ;done
+	trackpkg
 }
 
 chk_pkg() {
-  for i in $(cut -d: -f1 $conf) ;do
-    j=$(grep "^$i" $conf | cut -d: -f1)
-    k=$(grep "^$i" $conf | cut -d: -f2)
-    # echo $j :: $k
-    l=$($wrappaur -Ss $j)
-    [ "$k" = "$l" ] && echo $k || echo "$k  =>  $l"
-  done
+	for i in $(cut -d: -f1 $conf) ;do
+		j=$(grep "^$i" $conf | cut -d: -f1)
+		k=$(grep "^$i" $conf | cut -d: -f2)
+		# echo $j :: $k
+		l=$($wrappaur -Ss $j)
+		[ "$k" = "$l" ] && echo $k || echo "$k  =>  $l"
+	done
 }
 
 if   [ -z $1 ]                           ;then chk_pkg
diff --git a/bin/bin/functions/package/bundle_install b/bin/bin/functions/package/bundle_install
--- a/bin/bin/functions/package/bundle_install
+++ b/bin/bin/functions/package/bundle_install
@@ -38,18 +38,18 @@ unset HTTP_PROXY      # ignore local network proxy
 
 # distro package manager
 if exists pacman ;then
-  INSTALL=pm_install    # arch
-  QUERY='pacman -Q'
+	INSTALL=pm_install    # arch
+	QUERY='pacman -Q'
 else
-  INSTALL='xb_install'  # void
-  QUERY='xbps-query -S'
+	INSTALL='xb_install'  # void
+	QUERY='xbps-query -S'
 fi
 
 case $1 in
-  alpine) check=true; alpine=true;                      shift ;;
-  check ) check=true; gems=$(gem list | cut -d' ' -f1); shift ;;
-  list  ) list=true;                                    shift ;;
-  init  ) init=--init;                                  shift ;;
+	alpine) check=true; alpine=true;                      shift ;;
+	check ) check=true; gems=$(gem list | cut -d' ' -f1); shift ;;
+	list  ) list=true;                                    shift ;;
+	init  ) init=--init;                                  shift ;;
 esac
 
 echo $1 | grep -q '/' && BDIR=${1%/*} || BDIR=.
@@ -57,108 +57,109 @@ deferred=$BDIR/900-deferred
 missing=$BDIR/910-missing
 [ $check ] && rm -f $missing
 echo $@ | grep -q 900-deferred && unset deferred || {
-  [ $list ] || [ $alpine ] || { [ -e $deferred ] && { ifno 'clear last defer bundle' || rm $deferred; } }
+	[ $list ] || [ $alpine ] || { [ -e $deferred ] && { ifno 'clear last defer bundle' || rm $deferred; } }
 }
 
 rule() { echo "$@" | sed 's/\[//; s/\]//' || echo true; }
 
 # bundle file -> [<action>] <package> [<condition>]
 parse() {
-  case $action in
-    ''       ) return 1 ;;
-    '#'      ) return 1 ;;
-    '='      ) [ $list ] || { echo $package | grep -q '^[[:alpha:]]' && title "$package $condition"; }; return 1 ;;
-    '"'      ) [ $check ] || ditto "$package $condition";                                               return 1 ;;
-    '!'      ) [ $check ] || $package $condition;                                                       return 1 ;;
-    '+'      ) [ $list ] || { [ -z $check ] && { heading "[ Manual install required.. ]  $package";     return 1; } } ;;
-    d        ) rule=true ;;
-    g        ) version=$condition ;;
-    [-?@amps]) rule=$(rule "$condition") ;;
-  
-    *        ) set -- $package $condition
-               package=$action
-               condition=$@
-               rule=$(rule "$condition") ;;
-  esac
-  return 0
+	case $action in
+		''       ) return 1 ;;
+		'#'      ) return 1 ;;
+		'='      ) [ $list ] || { echo $package | grep -q '^[[:alpha:]]' && title "$package $condition"; }; return 1 ;;
+		'"'      ) [ $check ] || ditto "$package $condition";                                               return 1 ;;
+		'!'      ) [ $check ] || $package $condition;                                                       return 1 ;;
+		'+'      ) [ $list ] || { [ -z $check ] && { heading "[ Manual install required.. ]  $package";     return 1; } } ;;
+		d        ) rule=true ;;
+		g        ) version=$condition ;;
+		[-?@amps]) rule=$(rule "$condition") ;;
+	
+		*        )
+			set -- $package $condition
+			package=$action
+			condition=$@
+			rule=$(rule "$condition") ;;
+	esac
+	return 0
 }
 
 check() {
-  # check deferred actions
-  [ $action = d ] && [ "${package#?}" = '' ] && { action=$package; package=${condition%% *}; condition=${condition#* }; }
-  unset installed
-  if [ $alpine ] ;then
-    package=$(echo $package | sed 's/^python3-/py3-/; s/-devel$/-dev/')  # prefix/suffix name mapping
-    curl --silent "https://pkgs.alpinelinux.org/packages?name=$package&branch=edge&repo=main&arch=x86_64&maintainer=" 2>/dev/null | grep -q "No item found..." && 
-    curl --silent "https://pkgs.alpinelinux.org/packages?name=$package&branch=edge&repo=community&arch=x86_64&maintainer=" 2>/dev/null | grep -q "No item found..." && 
-    ditto ERROR "${RED}!match" $package || ditto alpine $package
-    return
-  fi
-  set -- $action $package $condition
-  action=$1;              shift
-  package=$1; [ "$1" ] && shift
-  condition=$@
-  parse || return
-  [ "$package" = "$action" ] && unset action
-  [ "$package" = "$condition" ] && unset condition
+	# check deferred actions
+	[ $action = d ] && [ "${package#?}" = '' ] && { action=$package; package=${condition%% *}; condition=${condition#* }; }
+	unset installed
+	if [ $alpine ] ;then
+		package=$(echo $package | sed 's/^python3-/py3-/; s/-devel$/-dev/')  # prefix/suffix name mapping
+		curl --silent "https://pkgs.alpinelinux.org/packages?name=$package&branch=edge&repo=main&arch=x86_64&maintainer=" 2>/dev/null | grep -q "No item found..." && 
+		curl --silent "https://pkgs.alpinelinux.org/packages?name=$package&branch=edge&repo=community&arch=x86_64&maintainer=" 2>/dev/null | grep -q "No item found..." && 
+		ditto ERROR "${RED}!match" $package || ditto alpine $package
+		return
+	fi
+	set -- $action $package $condition
+	action=$1;              shift
+	package=$1; [ "$1" ] && shift
+	condition=$@
+	parse || return
+	[ "$package" = "$action" ] && unset action
+	[ "$package" = "$condition" ] && unset condition
 
-  case $action in
-    '-') return ;;
-    '"') return ;;
-    g  ) echo "$gems" | grep -q "^$package$" && installed=true ;;
-    m  ) ;;  # cannot verify a make_install
-    *  ) $QUERY $package >/dev/null 2>&1 && installed=true ;;
-  esac
+	case $action in
+		'-') return ;;
+		'"') return ;;
+		g  ) echo "$gems" | grep -q "^$package$" && installed=true ;;
+		m  ) ;;  # cannot verify a make_install
+		*  ) $QUERY $package >/dev/null 2>&1 && installed=true ;;
+	esac
 
-  [ $installed ] && echo $package || { echo $line >>$missing ; ditto ERROR missing "$package"; }
+	[ $installed ] && echo $package || { echo $line >>$missing ; ditto ERROR missing "$package"; }
 }
 
 decomment() { echo "$@" | sed 's/#.*//'; }
 
 for i in $@ ;do
-  [ $list ] || subject $(basename $i | cut -d- -f2-9)
+	[ $list ] || subject $(basename $i | cut -d- -f2-9)
 
-  # preserve stdin fd for package manager prompts
-  # Note: (action package) map to (package condition) for default noconfirm install
-  #       (package condition) map to (command options) for ! execute
-  while read action package condition <&3 ;do
-    # echo "action=$action package=$package condition=$condition"
-    [ "$package" = '#' ] && unset package condition || condition=$(decomment $condition)
-    line="$action $package $condition"
-    parse || continue
+	# preserve stdin fd for package manager prompts
+	# Note: (action package) map to (package condition) for default noconfirm install
+	#       (package condition) map to (command options) for ! execute
+	while read action package condition <&3 ;do
+		# echo "action=$action package=$package condition=$condition"
+		[ "$package" = '#' ] && unset package condition || condition=$(decomment $condition)
+		line="$action $package $condition"
+		parse || continue
 
-    [ $list ] && { echo "$action $package $condition" | sed -r '/^d "/d; s/^([-?*@"adgm] )*//; s/ *([^ ]*).*/\1/'; continue; }
-    [ $alpine ] || { eval $rule || continue; }
-    [ $check ] && { check; continue; }
+		[ $list ] && { echo "$action $package $condition" | sed -r '/^d "/d; s/^([-?*@"adgm] )*//; s/ *([^ ]*).*/\1/'; continue; }
+		[ $alpine ] || { eval $rule || continue; }
+		[ $check ] && { check; continue; }
 
-    # package management
-    case $action in
-      '-') heading "--Uninstalling--  $package"; pm R $package ;;
-      '?') $INSTALL --confirm $package ;;
-      '@') aur_install $package ;;
-      a  ) arm_install $package ;;
-      d  ) echo "$package $condition" >>$deferred ;;
-      g  ) gem_install $package $version ;;
-      m  ) make_install $package ;;
-      p  ) pkg_install $package ;;
-      s  ) src_install $package ;;
-      *  ) $INSTALL $init $package ;;
-    esac
-  done 3< $i
+		# package management
+		case $action in
+			'-') heading "--Uninstalling--  $package"; pm R $package ;;
+			'?') $INSTALL --confirm $package ;;
+			'@') aur_install $package ;;
+			a  ) arm_install $package ;;
+			d  ) echo "$package $condition" >>$deferred ;;
+			g  ) gem_install $package $version ;;
+			m  ) make_install $package ;;
+			p  ) pkg_install $package ;;
+			s  ) src_install $package ;;
+			*  ) $INSTALL $init $package ;;
+		esac
+	done 3< $i
 done
 
 [ $list ] || [ $alpine ] && exit
 if [ $check ] && [ -e $missing ] ;then
-  # sort -u -o $missing $missing
-  sed -i 's/^d //' $missing
-  ditto ERROR missing "$(wc -l $missing | cut -d' ' -f1) packages"
-  cat $missing
-  ditto INFO "m make_install packages cannot be verified"
-  ifno "bundle_install $missing" || exec bundle_install $missing
+	# sort -u -o $missing $missing
+	sed -i 's/^d //' $missing
+	ditto ERROR missing "$(wc -l $missing | cut -d' ' -f1) packages"
+	cat $missing
+	ditto INFO "m make_install packages cannot be verified"
+	ifno "bundle_install $missing" || exec bundle_install $missing
 elif [ $deferred ] && [ -e $deferred ] ;then
-  # sort -u -o $deferred $deferred
-  cat $deferred
-  ifno "bundle_install $deferred" || exec bundle_install $deferred
+	# sort -u -o $deferred $deferred
+	cat $deferred
+	ifno "bundle_install $deferred" || exec bundle_install $deferred
 fi
 
 # vim: set ft=sh: 
diff --git a/bin/bin/functions/query/gpu b/bin/bin/functions/query/gpu
--- a/bin/bin/functions/query/gpu
+++ b/bin/bin/functions/query/gpu
@@ -9,31 +9,29 @@
 usage() { usage: "$(basename $0) [display | nvidia | ati | intel | macbook]"; }
 
 vga() {
-  lspci 2>/dev/null | grep VGA | grep -qi "$1" || return 1
-  echo $1
-  card=true
-  return 0
+	lspci 2>/dev/null | grep VGA | grep -qi "$1" || return 1
+	echo $1
+	card=true
+	return 0
 }
 
 case $1 in
-  ''      ) vga Intel
-            vga NVIDIA
-            vga ATI
-            vga 'GeForce 8600M GT'
-            vga 'GeForce GT 650M'
-            
-            # lspci fails on raspberry pi
-            [ $card ] || echo arm ;;
-  
-  display ) xrandr 2>/dev/null | grep '*' | awk '{ print $1 }' ;;
-  
-  ati       |\
-  intel     |\
-  nvidia  ) vga $1 >/dev/null ;;
-  
-  macbook ) vga 'GeForce 8600M GT' >/dev/null ;;
-  inspiron) vga 'GeForce GT 650M'  >/dev/null ;;
-  *       ) usage ;;
+	''      )
+		vga Intel
+		vga NVIDIA
+		vga ATI
+		vga 'GeForce 8600M GT'
+		vga 'GeForce GT 650M'
+		# lspci fails on raspberry pi
+		[ $card ] || echo arm ;;
+	
+	display ) xrandr 2>/dev/null | grep '*' | awk '{ print $1 }' ;;
+	ati     |\
+	intel   |\
+	nvidia  ) vga $1 >/dev/null ;;
+	macbook ) vga 'GeForce 8600M GT' >/dev/null ;;
+	inspiron) vga 'GeForce GT 650M'  >/dev/null ;;
+	*       ) usage ;;
 esac
 
 # vim: set ft=sh: #
diff --git a/bin/bin/functions/ui/ifno b/bin/bin/functions/ui/ifno
--- a/bin/bin/functions/ui/ifno
+++ b/bin/bin/functions/ui/ifno
@@ -12,16 +12,16 @@ sig=${sig:--TERM}
 underline ${YELLOW}$@
 
 while : ;do
-  printf "${TEAL}continue? ${RED}[No]${NOCOLOR}/yes/abort : "
-  # using bash's extended read functionality (over dash) for single character input
-  IFS= read -rn1 CONTINUE
-  echo
-  case $CONTINUE in
-    ''  ) exit 0 ;;
-    [nN]) exit 0 ;;
-    [yY]) exit 1 ;;
-    [aA]) { kill $sig ${TMPPID:-$PPID}; break; } ;;  # see tmout
-  esac
+	printf "${TEAL}continue? ${RED}[No]${NOCOLOR}/yes/abort : "
+	# using bash's extended read functionality (over dash) for single character input
+	IFS= read -rn1 CONTINUE
+	echo
+	case $CONTINUE in
+		''  ) exit 0 ;;
+		[nN]) exit 0 ;;
+		[yY]) exit 1 ;;
+		[aA]) { kill $sig ${TMPPID:-$PPID}; break; } ;;  # see tmout
+	esac
 done
 
 # vim: set ft=sh: #
