usage messaging

diff --git a/bin/bin/functions/shell/usage: b/bin/bin/functions/shell/usage:
--- a/bin/bin/functions/shell/usage:
+++ b/bin/bin/functions/shell/usage:
@@ -16,14 +16,13 @@ if [ "$1" ] ;then
     name=$(basename $1)
     message="$name $(ls -1 $(dirname $1)/functions/$name | tr '\n' ' ' | sed 's/ / \| /g')"
   fi
-
   echo "${BROWN}Usage: ${WHITE}$(echo "${message:-$1}" | sed -r "s/^ *([^ ]+ )/\1${cyan}/")${NOCOLOR}"
-  exit 1
 else
   cat >$USAGE
   command=$(head -1 $USAGE | cut -d' ' -f1)
-  echo "${BROWN}Usage: $(sed -r "s/($command )/${WHITE}\1${cyan}/g; s/^< /  /g; s/^/       /g; 1s/^ *//;" $USAGE)"  # "< " anti-tab
-  # exit 1  # is responsibility of calling script 
+  echo "${BROWN}Usage: $(sed -r "s/($command )/${WHITE}\1${cyan}/g; s/^< /  /g; s/^/       /g; 1s/^ *//;" $USAGE)"  # "< " anti-tab (space) placeholder
 fi
+
+exit 1  # return code only (no termination) for ".. | usage:"
 
 # vim: set ft=sh: #
